### ISSUE TITLE
Release v0.3.0 requirements

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#116]
**Must have**
- [x]  RollingUpdate with MaxSurge support #3
- [x]  Add a new condition UpdateInProgress and UpdateComplete #106 
- [x]  Subgroup support for disaggregated serving on TPU #115
- [x] Add example for multi-host serving of llama 70B on GPUs #124 
- [x] Add a new start policy API #135
- [x] Inject leader address environment variable to every container #143 
- [x] spec.rolloutStrategy should be a non-required field #147

**Comment by kerthcet** [comment]
Should we include subGroupSize here @liurupeng? Seems it will be finished in prior of `UpdateInProgress` @liurupeng

**Comment by liurupeng** [comment]
@kerthcet the subGroupSize one is the third one right?

**Comment by kerthcet** [comment]
ah yes, my mistake, but it's closed unexpected.

**Comment by kerthcet** [comment]
ah yes, my mistake, but it's closed unexpected.

**Comment by kerthcet** [comment]
Would like to include https://github.com/kubernetes-sigs/lws/issues/147 as a change to the API field.

**Comment by liurupeng** [comment]
ok, sg!

**Comment by kerthcet** [comment]
We're ready to fire now @liurupeng
