### ISSUE TITLE
Release v0.4.0 requirements

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#161]
```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/lws/pull/163
- [ ] https://github.com/kubernetes-sigs/lws/issues/173
- [ ] https://github.com/kubernetes-sigs/lws/pull/176
- [ ] https://github.com/kubernetes-sigs/lws/issues/204
- [ ] https://github.com/kubernetes-sigs/lws/issues/203
- [ ] https://github.com/kubernetes-sigs/lws/pull/174
- [ ] https://github.com/kubernetes-sigs/lws/pull/185
```

**Comment by kerthcet** [comment]
Maybe we can have an example for disaggregated serving.

**Comment by liurupeng** [comment]
@kerthcet right now we don't have something public for the example, probably with release v0.5.0

**Comment by ahg-g** [comment]
@liurupeng can we plan for the next release and decide on a date please?

**Comment by ahg-g** [comment]
A couple more: 
- https://github.com/kubernetes-sigs/lws/issues/204
- https://github.com/kubernetes-sigs/lws/issues/203

**Comment by liurupeng** [comment]
sg! thanks @ahg-g

**Comment by liurupeng** [comment]
Target release date will be Sep 13

**Comment by kerthcet** [comment]
Should we release today, I'm waiting for the feature https://github.com/kubernetes-sigs/lws/pull/190, I can pick the left one.

**Comment by liurupeng** [comment]
@kerthcet sure, feel free to pick up this one

**Comment by kerthcet** [comment]
Created https://github.com/kubernetes-sigs/lws/pull/214

**Comment by ahg-g** [comment]
@kerthcet do you want to create the release?

**Comment by liurupeng** [comment]
Sorry for the delay, just created the release. Please approve the release, thanks! @ahg-g @kerthcet

**Comment by kerthcet** [comment]
Maybe we can start with milestone next release? But seems we still need a release issue for discussion?

**Comment by liurupeng** [comment]
@kerthcet do you want to drive the next release?

**Comment by kerthcet** [comment]
I'll keep an eye on this and try to track with milestone as well.
