### ISSUE TITLE
Release v0.5.0 requirements

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#221]
```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/lws/issues/243
- [ ] https://github.com/kubernetes-sigs/lws/pull/277
- [ ] https://github.com/kubernetes-sigs/lws/issues/215
- [ ] https://github.com/kubernetes-sigs/lws/pull/209
- [ ] https://github.com/kubernetes-sigs/lws/issues/225
```

**Comment by liurupeng** [comment]
I have added all the items to the task list, we may not necessarily support all of them, we will update once finalized

**Comment by kannon92** [comment]
Could you please add a potential date you'd like to target?

**Comment by liurupeng** [comment]
@kannon92 yep, I would target Nov 15 as the next release date

**Comment by ahg-g** [comment]
New target is late January, the key feature we need is controller-revision to address the issues related to replica restarts on controller upgrade.

**Comment by ahg-g** [comment]
All requirements are now addressed. Release issue: https://github.com/kubernetes-sigs/lws/issues/302

**Comment by ahg-g** [comment]
Yes, but we already have a major feature pushed in this planned release, I know this is https://github.com/kubernetes-sigs/lws/pull/284 is not a major feature, but I don't feel confident that we tested it well enough. I would like to move forward with the release to ensure we have an incremental releases.
