### ISSUE TITLE
Release v0.2.0 requirements

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#66]
**Must have**
- [x] Rollout and RollingUpdate #39
- [x] Allow Prometheus to collect metrics from controller-runtime #45 
- [x] E2E test setup and coverage #6 
- [x] Add example for using Saxml for multi-host inference #59 
- [x] Fix leader/worker pods TPU environment variables population issue #61 
- [x] Allow setting publishNotReadyAddresses=True when creating headless service #85

**Comment by ahg-g** [comment]
@kerthcet

**Comment by ahg-g** [comment]
Can you please link each item to issue tracking it.

**Comment by liurupeng** [comment]
@ahg-g done!

**Comment by kerthcet** [comment]
SGTM

**Comment by kerthcet** [comment]
I think we're ready to release 0.2.0.

**Comment by kerthcet** [comment]
> I think we're ready to release 0.2.0.

Seems still have some discussion about condition replicas.

**Comment by liurupeng** [comment]
@kerthcet actually I feel we could keep the current semantics for updatedReplicas as it is, adding a new condition to record the update status is sufficient already, wdyt

**Comment by kerthcet** [comment]
Worth to have a try!
